---
- name: Discover/backup hosts to be migrated
  hosts: migration-hosts
#  gather_facts: false
  vars:
    # The host to store backup info to
    backup_storage: backup-storage

    # The location on the backup host to store info
    backup_location: /tmp/migration
  tasks:
  - name: Debug gathered gather_facts
    ansible.builtin.debug:
      var: ansible_facts
      
  - name: Create backup directory on backup server - unique for each host
    ansible.builtin.file:
      path: "{{ backup_location }}/{{ inventory_hostname }}"
      state: directory
      mode: '0733'
    delegate_to: "{{ backup_storage }}"

  # - name: Backup groups
  #   ansible.builtin.include_tasks:
  #     file: group-backup.yml

  - name: Backup Apache
    ansible.builtin.include_tasks:
      file: apache-backup.yml 