---
- name: Playbook to restore configs on new servers
  hosts: migration-hosts # Greg-rocky9-2
  gather_facts: false
  vars:
    # The host to store backup info to
    backup_storage: backup-storage

    # The location on the backup host to store info
    backup_location: /tmp/migration

  tasks:
  # grab a list of the files on the backup server for this host
  - name: Find all files in hosts' backup directories
    ansible.builtin.find:
      paths: "{{ backup_location }}/{{ inventory_hostname }}"
#      recurse: yes
    delegate_to: "{{ backup_storage }}"
    register: config_files

  - name: Debug config_files
    when: item.path is search(inventory_hostname + '-httpd.tgz')
    ansible.builtin.debug:
      var: config_files
    loop: "{{ config_files.files }}"

  # for each task type, loop through backup files and see if they exist - call restore task file