---
- name: Provision a new server in VMWare
  hosts: migration-hosts
  gather_facts: false
  vars:
    # vcenter variables should be passed in at run time.  I'm using a custom credential in tower.
#    vcenter_hostname: 10.1.2.3
    vcenter_username: "{{ gen1_user }}"
    vcenter_password: "{{ gen1_pword }}"

    # below are all of the details for the VM.  I'm overriding these at runtime.
    vm_datacenter: MNS
    vm_folder: /Greg/ciq

  tasks:
  - name: Suspend the old virtual machine
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "{{ vm_folder }}"
      datacenter: "{{ vm_datacenter }}"
      name: "{{ inventory_hostname }}"
      state: suspended
    delegate_to: localhost